name: dpm
author: Serge Shkurko <SergeShkurko@outlook.com>
version: 0.1.1
homepage: https://github.com/rbcprolabs/dpm
description: Run commands upon installing & upgrades packages, powerfull package management with CLI. Flutter cappatible!
environment:
  sdk: '>=2.3.0-dev.0.5 <3.0.0'
dependencies:
  quiver: ^2.0.3
  args: ^1.5.2
  collection: ^1.14.11
  http: ^0.12.0+2
  pub_semver: ^1.4.2
  console: ^3.1.0
  path: ^1.6.2
  meta: ^1.1.7
  pubspec: ^0.1.1
  # pubspec:
  #   git:
  #     url: git://github.com/SergeShkurko/pubspec.git
  #     ref: master
  register: ^1.0.0
  yaml: ^2.1.16
  colorize: ^2.0.0
  tuple: ^1.0.2
  yamlicious: ^0.1.0
dev_dependencies:
  test: ^1.6.5
  pedantic: ^1.8.0+1
executables:
  dpm: dpm
